language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson desktop-file-utils gettext libaccountsservice-dev libgtk-3-dev libgee-0.8-dev libgranite-dev libxml2-dev libjson-glib-dev libgnomekbd-dev libpolkit-gobject-1-dev libpwquality-dev libxml2-utils valac"

install:
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:stable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build && ninja -C build"
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && rm -rf build && meson build && ninja -C build"

script:
 - echo BUILDS PASSED
